server:
   port: 9001
   error:
      include-stacktrace: "never"

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
      
springdoc:
  swagger-ui:
    path: /department/swagger-ui.html
  api-docs:
    path: /department/v3/api-docs/
    
spring: 
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/department_service
      username: root
      password: hhhvn@db2021
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
   mvc:
      pathmatch:
         matching-strategy: ant_path_matcher
