server:
   port: 8888

spring:
   application:
      name: config-server
#   use native file in config server      
   profiles:
       active: native   
       
#   use with git      
#   cloud:
#      config:
#         server:
#            git:
#               uri: https://github.com/micro-services-mrbin2903/config-repo
#               default-label: main
#            bootstrap: false  

 